language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - pypy
install:
  - pip install -r requirements/testing.txt -r requirements/production.txt --use-mirrors
  - python setup.py install
script: python setup.py test
notifications:
    email:
      recipients:
        - aaron.iles+travis-ci@gmail.com
        - mjdorma+travis-ci@gmail.com
      on_success: change
      on_failure: always
